# This is the configuration used to check the rubocop source code.
AllCops:
  Exclude:
    - 'config/**/*'
    - 'bin/**/*'
    - 'lib/blender.rb'
  CacheRootDirectory: '../../tmp'

Style/GuardClause:
  Enabled: false

Style/WordArray:
  MinSize: 3

Style/SymbolProc:
  IgnoredMethods: validate

Style/Documentation:
  Enabled: false

Style/AndOr:
  EnforcedStyle: conditionals

Metrics/LineLength:
  Max: 89

Style/AlignHash:
  EnforcedLastArgumentHashStyle: 'ignore_implicit'

Style/AlignParameters:
  Enabled: false
